Add Death-Branded Shatterer to worldbosses
gw2efficiency/static-data pull request #20
Opened 2024-02-04 15:39 UTC by Ecmelt

2024-02-04 15:40 UTC, Ecmelt commented
I am not sure which icon should be used for this, any suggestions? Or i could create one myself.

2024-02-04 16:54 UTC, queicherius commented
I'd say whatever you think feels right. Some inspiration:
- https://wiki.guildwars2.com/wiki/Smoky_Brand_Crystal
- https://wiki.guildwars2.com/wiki/Breath_of_Kralkatorrik_(fine)
- https://wiki.guildwars2.com/wiki/Crystal_Infusion

2024-02-04 16:55 UTC, queicherius requested changes
LGTM, waiting for the icon

2024-02-05 18:32 UTC, queicherius approved these changes

2024-02-05 18:32 UTC, merged